name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'df3raeh*23r'
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Shutdown application
        run: (php artisan down) || true

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, mysql
          tools: composer:v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update application
        run: |
          git pull

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mysql -uroot -ppassword -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS laravel;'
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run Migrations
        run: php artisan migrate --force
        env:
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: 'df3raeh*23r'

      - name: Run Tests
        run: php artisan test

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: npm install
      - run: npm run build

      - run: php artisan up
    # Additional steps for deployment can be added here if needed
    # - name: Deploy to Production
    #   run: <deployment-command>
    #   env:
    #     DEPLOYMENT_SECRET: ${{ secrets.DEPLOYMENT_SECRET }}

