name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: npm install
      - run: npm run build
      - name: Commit built assets
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "GitHub Action"
          git checkout -B main
          git add -f public/
          git commit -m "Build front-end assets"
          git push -f origin main
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.ED25519 }}
          script: |
            cd /var/www/html
            .github/scripts/server_deploy.sh
